version: 2

jobs:
  build:
    docker:
      - image: quay.io/rust-lang-ja/circleci:edition-guide-mdbook-0.4.13
    steps:
      - checkout
      - run: rustc --version --verbose
      - run: cargo --version --verbose
      - run: mdbook --version
      - run:
          name: Building book
          command: mdbook build --dest-dir ./docs
      - run:
          name: Creating artifact
          command: |
            cp -rp docs /tmp/docs
            tar cJf docs.txz docs
            mv docs.txz /tmp
      - store_artifacts:
          path: /tmp/docs
          destination: docs
      - store_artifacts:
          path: /tmp/docs.txz
          destination: docs.txz
      - run:
          name: Testing book
          command: mdbook test
      # - run:
      #     name: Check for broken links
      #     command: |
      #       curl -sSLo linkcheck.sh \
      #         https://raw.githubusercontent.com/rust-lang/rust/master/src/tools/linkchecker/linkcheck.sh
      #       sh linkcheck.sh --all edition-guide
      - run:
          name: If master branch, publish to GitHub Page
          command: |
            if [ "x_${CIRCLE_BRANCH}" == "x_master" ]; then
              git config user.name "bn-e (CircleCI)"
              git config user.email "bn-e@hibaridb.org"
              ./tools/circleci/push-to-master.sh
            fi
